# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshsign < Formula
  desc "SSH signing service CLI for AI agents"
  homepage "https://sshsign.dev"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agenticpoa/sshsign/releases/download/v0.2.0/sshsign_darwin_amd64.tar.gz"
      sha256 "2035d0406a4fa933685aba92fc1e04ac33ef14e213a9a071040bee06acf8165b"

      define_method(:install) do
        bin.install "sshsign"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agenticpoa/sshsign/releases/download/v0.2.0/sshsign_darwin_arm64.tar.gz"
      sha256 "1439a464354081e0e56b246200c0d0efeb0f95c2a50af5bb6e7043dd9fe705fd"

      define_method(:install) do
        bin.install "sshsign"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agenticpoa/sshsign/releases/download/v0.2.0/sshsign_linux_amd64.tar.gz"
      sha256 "5f42362dcb5474fca59f56861c256d82e6c3f23f4096df66eb4d205355d0fbed"
      define_method(:install) do
        bin.install "sshsign"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agenticpoa/sshsign/releases/download/v0.2.0/sshsign_linux_arm64.tar.gz"
      sha256 "b7fdfe3b99de0166f9c8bf98b86872e658748fdf26e5e13a53cd522e90911929"
      define_method(:install) do
        bin.install "sshsign"
      end
    end
  end
end
